use demo;
select * from employees where salary > 50000;
select * from products where price between 100 and 500;
select * from customers where city in ('Hyderabad','Banglore');
select * from orders where orderdate > '2023-01-01';
select * from employees where employeeName like 'A%';
select deptName from employees where avg(salary)>40000;
select productCategory from products where sum(sales)>10000;
select customerID from orders group by customerid having count(orderID)>5;
select supplierName from suppliers where quantity<50;
select city from customers group by city having count(customerid)>100;
select * from employees order by joiningDate asc;
select customerName,city from customers order by city;
select orderID,orderDate from orders order by orderDate asc,orderAmount desc;
select * from movies order by releaseYear desc,title asc;
select * from employee where salary >40000 order by employeeName;
select productName,sum(qty) as totalSales from products group by productID having totalSales >20 order by totalSales desc;
select * from orders where orderAmount>5000 group by customerID having count(orderID)>3 order by orderAmount;  
select * from students where grade>75 order by grade desc;
select productName,sum(qty) as total_sales from products group by productId order by sum(qty) limit 5;